In [95]:
import pandas as pd 
import numpy as np 
from pandas_profiling import ProfileReport

import seaborn as sns  
import matplotlib.pyplot as plt

# plt.rcParams['figure.dpi'] = 150
# plt.style.use('seaborn-deep')
# pd.set_option('display.max_columns', None)

/Users/vasevooo/projects/EDA-Real-Estate/env/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/fx/mm163gs50sg284cn4dbq0dlh0000gn/T/ipykernel_47996/2964933821.py:3: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport
/var/folders/fx/mm163gs50sg284cn4dbq0dlh0000gn/T/ipykernel_47996/2964933821.py:9: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-deep')

## EDA

1. Описание дата сета 
2. разбивка по городам - Москва и СПБ
3. количество фич с пустыми значениями
4. Планируем удалить "перечень колонок"
5. План действий: заполнить NaN, обработать текстовые значения

In [104]:
path = ('/Users/vasevooo/projects/EDA-Real-Estate/_data.csv')
df = pd.read_csv(path, index_col= 0)
df.head(5)

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,Описание,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.0,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.5,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт,14-42-20-19,NaN,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт,20 18,NaN,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.9,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615

In [111]:
## Какие колонки можно дропнуть? 
# Тип, Серия дома, название ЖК(??), Телефон, Ссылка на объявление, Описание

# df = df.drop(columns=['Серия дома', 'Тип', 'Телефоны', 'Ссылка на объявление'])



df = df.drop_duplicates(subset=['ID  объявления'], keep='first').reset_index(drop = True) #Можно дропнуть по ID дубликаты, но их и нет
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23368 entries, 0 to 23367
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID  объявления            23368 non-null  int64
 1   Количество комнат         22327 non-null  object
 2   Тип                       23368 non-null  object
 3   Метро                     22053 non-null  object
 4   Адрес                     23368 non-null  object
 5   Площадь, м2               23368 non-null  object
 6   Дом                       23368 non-null  object
 7   Парковка                  9951 non-null   object
 8   Цена                      23368 non-null  object
 9   Телефоны                  23368 non-null  object
 10  Описание                  23368 non-null  object
 11  Ремонт                    20613 non-null  object
 12  Площадь комнат, м2        14458 non-null  object
 13  Балкон                    15390 non-null  object
 14  Окна                      16755 non-null  object
 15  Санузел                   20696 non-null  object
 16  Можно с детьми/животными  17272 non-null  object
 17  Дополнительно             23011 non-null  object
 18  Название ЖК               5848 non-null   object
 19  Серия дома                2163 non-null   object
 20  Высота потолков, м        11206 non-null  float64
 21  Лифт                      17868 non-null  object
 22  Мусоропровод              12846 non-null  object
 23  Ссылка на объявление      23368 non-null  object
dtypes: float64(1), int64(1), object(22)
memory usage: 4.3+ MB

In [105]:
df.isna().sum().sort_values(ascending=False)

Серия дома                  21205
Название ЖК                 17520
Парковка                    13417
Высота потолков, м          12162
Мусоропровод                10522
Площадь комнат, м2           8910
Балкон                       7978
Окна                         6613
Можно с детьми/животными     6096
Лифт                         5500
Ремонт                       2755
Санузел                      2672
Метро                        1315
Количество комнат            1041
Дополнительно                 357
ID  объявления                  0
Описание                        0
Телефоны                        0
Цена                            0
Дом                             0
Площадь, м2                     0
Адрес                           0
Тип                             0
Ссылка на объявление            0
dtype: int64

In [106]:
df.shape

(23368, 24)

In [107]:
(df.isnull().mean() * 100).sort_values(ascending=False)

Серия дома                  90.743752
Название ЖК                 74.974324
Парковка                    57.416125
Высота потолков, м          52.045532
Мусоропровод                45.027388
Площадь комнат, м2          38.129065
Балкон                      34.140705
Окна                        28.299384
Можно с детьми/животными    26.086957
Лифт                        23.536460
Ремонт                      11.789627
Санузел                     11.434440
Метро                        5.627354
Количество комнат            4.454810
Дополнительно                1.527730
ID  объявления               0.000000
Описание                     0.000000
Телефоны                     0.000000
Цена                         0.000000
Дом                          0.000000
Площадь, м2                  0.000000
Адрес                        0.000000
Тип                          0.000000
Ссылка на объявление         0.000000
dtype: float64

In [113]:
# df = df.drop(columns=['Серия дома'])
df[(df['Количество комнат'].isna() == True )]

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,Описание,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
115,271827359,NaN,Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 32",41.0,10/13,NaN,"180000.0 руб./ За месяц, Залог - 180000 руб., ...",+79651989679,ID 669. С коллегами работаем 50/50. Видовые ап...,Дизайнерский,NaN,NaN,NaN,NaN,NaN,"Мебель в комнатах, Мебель на кухне, Душевая ка...",Звёзды Арбата,NaN,NaN,NaN,NaN,https://www.cian.ru/rent/flat/271827359
120,272559990,NaN,Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 32",63.0,2/13,NaN,"270000.0 руб./ За месяц, Залог - 270000 руб., ...",+79651989679,ID 21. С коллегами работаем 50/50. Апартаменты...,Дизайнерский,NaN,NaN,NaN,NaN,NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Тел...",Звёзды Арбата,NaN,NaN,NaN,NaN,https://www.cian.ru/rent/flat/272559990
270,273672956,NaN,Квартира,м. Алтуфьево (15 мин на машине),"Москва, Дмитровское шоссе, 188, ш. Дмитровское...",26.0/5.0,3/3,NaN,"23000.0 руб./ За месяц, Залог - 23000 руб., Ко...",+79651067064,Сдаются апартаменты студия в частном доме для ...,Евроремонт,NaN,NaN,NaN,NaN,NaN,"Мебель в комнатах, Мебель на кухне, Душевая ка...",NaN,NaN,NaN,NaN,Нет,https://www.cian.ru/rent/flat/273672956
288,274792043,NaN,Квартира,м. Новодачная (29 мин пешком),"Москва, бульвар Академика Ландау, 5к1, ш. Дмит...",27.0,"9/9, Монолитный",NaN,"35000.0 руб./ За месяц, Залог - 35000 руб., Ко...","+79853073419, +79689471391",Сдаётся квартира-студия 27 кв.м с лоджией. Сда...,Косметический,NaN,Лоджия (1),На улицу,Совмещенный (1),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Душевая ка...",NaN,NaN,NaN,Пасс (2),NaN,https://www.cian.ru/rent/flat/274792043
289,274557406,NaN,Квартира,м. Новодачная (7 мин на машине),"Москва, бульвар Академика Ландау, 5к2, ш. Дмит...",27.7/13.4/6.8,"10/14, Монолитный",NaN,"35000.0 руб./ За месяц, Залог - 35000 руб., Ко...","+79853033675, +79646329886","Чистая, солнечная квартира. Коммунальные плате...",Косметический,NaN,NaN,NaN,NaN,NaN,"Мебель в комнатах, Мебель на кухне",NaN,NaN,NaN,Пасс (2),NaN,https://www.cian.ru/rent/flat/274557406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23334,240752358,NaN,Квартира,м. Говорово (4 мин пешком),"Москва, Боровское шоссе, 2к7, ш. Боровское (3 ...",23.0,6/25,наземная,"38000.0 руб./ За месяц, Залог - 40000 руб., Ко...",+79660640306,В квартире жила только девушка с ребёнком полг...,Евроремонт,NaN,NaN,Во двор,NaN,NaN,"Мебель в комнатах, Мебель на кухне, Душевая ка...","Мещерский лес, 2018",NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/240752358
23348,232956268,NaN,Квартира,м. Говорово (2 мин пешком),"Москва, Боровское шоссе, 2к6, ш. Боровское (3 ...",35.0,6/24,NaN,"50000.0 руб./ За месяц, Залог - 50000 руб., Ко...",+74954760059,Писать в WhatsApp\n\nСобственник\n\nЗаселение ...,Косметический,NaN,NaN,NaN,NaN,NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...","Мещерский лес, 2018",NaN,NaN,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/232956268
23353,264039838,NaN,Квартира,м. Солнцево (2 мин пешком),"Москва, Производственная улица, 2, ш. Боровско...",45.0/22.0/15.0,"12/23, Монолитно-кирпичный",NaN,"52000.0 руб./ За месяц, Залог - 52000 руб., Ко...",+79067953058,Я Собственник...\nВидовая квартира в доме бизн...,Евроремонт,NaN,Балкон (1),На улицу,Совмещенный (1),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",NaN,NaN,NaN,Пасс (3),Да,https://www.cian.ru/rent/flat/264039838
23362,274652877,NaN,Квартира,м. Говорово (8 мин пешком),"Москва, Боровское шоссе, 2Ак2, ш. Боровское (3...",25.0/17.0/4.0,"11/17, Монолитный",NaN,"39000.0 руб./ За месяц, Залог - 40000 руб., Ко...",+79645380903,Сдам студию без комиссий от собственника рядо...,Евроремонт,NaN,NaN,NaN,NaN,NaN,"Мебель в комнатах, Мебель на кухне, Душевая ка...","Мещерский лес, 2017",NaN,NaN,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/274652877
23363,215565511,NaN,Квартира,м. Говорово (8 мин пешком),"Москва, Боровское шоссе, 2к7, ш. Боровское (3 ...",35.0/16.4/8.0,10/14,NaN,"42000.0 руб./ За месяц, Залог - 42000 руб., Ко...",+79154383401,Сдаётся светлая теплая квартира (студия) с бал...,Евроремонт,NaN,Балкон (1),NaN,Совмещенный (1),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Сти...",Мещерский лес,NaN,NaN,"Пасс (1), Груз (1)",NaN,https://www.cian.ru/rent/flat/215565511

In [63]:
df['Парковка'].value_counts()

Парковка
наземная          6043
подземная         2772
открытая          1017
многоуровневая     118
на крыше             1
Name: count, dtype: int64

In [108]:
df['Количество комнат'].value_counts()

Количество комнат
1                   7917
2, Изолированная    4623
2                   2591
3                   1717
3, Изолированная    1583
3, Оба варианта      875
4                    674
2, Смежная           637
2, Оба варианта      615
4, Оба варианта      253
5                    235
4, Изолированная     223
6                     87
3, Смежная            87
5, Оба варианта       81
5, Изолированная      47
6, Оба варианта       31
6, Изолированная      17
4, Смежная            13
1, Изолированная       8
1, Оба варианта        4
5, Смежная             4
6, Смежная             3
1, Смежная             2
Name: count, dtype: int64

In [109]:
df['Дом'].value_counts()

Дом
3/5, Кирпичный               322
4/5, Кирпичный               296
2/5, Кирпичный               255
1/5, Кирпичный               232
5/5, Кирпичный               231
                            ...
19/35, Монолитный              1
8/35, Монолитно-кирпичный      1
12/49, Монолитный              1
13/34, Монолитный              1
12/25, Блочный                 1
Name: count, Length: 2565, dtype: int64

In [65]:
df['Высота потолков, м'].value_counts()

Высота потолков, м
2.64      4467
3.00      1322
2.70      1040
2.48       676
3.20       617
          ...
265.00       1
4.15         1
9.00         1
260.00       1
3.02         1
Name: count, Length: 95, dtype: int64

In [66]:
df['Мусоропровод'].value_counts()

Мусоропровод
Да     10897
Нет     1949
Name: count, dtype: int64

In [67]:
df['Балкон'].value_counts()

Балкон
Балкон (1)                7428
Лоджия (1)                6007
Балкон (1), Лоджия (1)     716
Лоджия (2)                 568
Балкон (2)                 474
Балкон (3)                  55
Лоджия (3)                  45
Балкон (2), Лоджия (2)      25
Балкон (1), Лоджия (2)      24
Балкон (2), Лоджия (1)      20
Балкон (4)                   6
Балкон (3), Лоджия (1)       5
Балкон (1), Лоджия (3)       5
Лоджия (4)                   5
Балкон (2), Лоджия (3)       3
Балкон (1), Лоджия (4)       2
Балкон (3), Лоджия (3)       1
Балкон (4), Лоджия (4)       1
Name: count, dtype: int64

In [68]:
df['Метро'].value_counts()

Метро
м. Академическая (10 мин пешком)            41
м. Водный стадион (5 мин пешком)            40
м. Приморская (None мин пешком)             35
м. Щелковская (15 мин пешком)               34
м. Динамо (7 мин пешком)                    33
                                            ..
м. Раменки (4 мин пешком)                    1
м. Студенческая (8 мин на машине)            1
м. Парк Победы (57 мин пешком)               1
м. Ломоносовский проспект (1 мин пешком)     1
м. Солнцево (5 мин на машине)                1
Name: count, Length: 5866, dtype: int64

In [114]:
df['Ремонт'].value_counts()

Ремонт
Косметический    8499
Евроремонт       8470
Дизайнерский     3474
Без ремонта       170
Name: count, dtype: int64

In [115]:
df['Окна'].value_counts()

Окна
Во двор            10870
На улицу и двор     3295
На улицу            2590
Name: count, dtype: int64

In [119]:
df['Дополнительно'].str.split(',')

0        [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
1        [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
2        [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
3        [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
4        [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
                               ...
23363    [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
23364    [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
23365    [Мебель на кухне,  Душевая кабина,  Стиральная...
23366    [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
23367    [Мебель в комнатах,  Мебель на кухне,  Ванна, ...
Name: Дополнительно, Length: 23368, dtype: object

In [71]:
df[['Площадь комнат, м2', 'Площадь, м2']]

      Площадь комнат, м2      Площадь, м2
0                    NaN       200.0/20.0
1            25 25 20 25  198.0/95.0/18.0
2                    NaN  200.0/116.0/4.0
3            14-42-20-19  170.0/95.0/17.0
4                  20 18    58.0/38.0/5.0
...                  ...              ...
23363                NaN    35.0/16.4/8.0
23364                NaN   38.7/16.5/11.0
23365                NaN             43.1
23366                NaN        52.5/10.0
23367     26,2+15,5-22,0   90.0/48.2/15.5

[23368 rows x 2 columns]

In [103]:
df[df['Адрес'].str.contains("Москва") == True]['Адрес'].count() # Надо будет оставить только Москву

19737

In [101]:
# profile = ProfileReport(df)
# profile